sudo: required
services:
  - docker

before_install:
  - docker build -t astrals63/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run astrals63/react-test npm test -- --coverage

after_success:
  - docker build -t astrals63/multi-client ./client
  - docker build -t astrals63/multi-nginx ./nginx
  - docker build -t astrals63/multi-server ./server
  - docker build -t astrals63/multi-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push astrals63/multi-client
  - docker push astrals63/multi-nginx
  - docker push astrals63/multi-server
  - docker push astrals63/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-870594606895
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY