sudo: required
services:
  - docker

before_install:
  - docker build -t astrals63/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run astrals63/react-test npm test -- --coverage

after_sucess:
  - docker build -t astrals63/multi-client ./client
  - docker build -t astrals63/multi-nginx ./nginx
  - docker build -t astrals63/multi-server ./server
  - docker build -t astrals63/multi-worker ./worker

  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push astrals63/multi-client
  - docker push astrals63/multi-nginx
  - docker push astrals63/multi-server
  - docker push astrals63/multi-worker
